/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\robot-1.gltf -K -k 
*/

import React, { useState } from 'react'
import { useFrame } from "@react-three/fiber";
import { useGLTF } from '@react-three/drei';
import { motion } from "framer-motion-3d";
import { Words } from "../Words";
import { useEffect } from "react";

export function Buny(props) {
  const { nodes, materials } = useGLTF('models/robots/buny_robot/buny.gltf');
  let { section, timeWait } = props;

  const [ validSkill, setValidSkill ] = useState(false);
  
  useEffect(() => {
    if (section === 1) {
      setTimeout(() => {
        setValidSkill(true);
      }, timeWait)
    } else {
        setValidSkill(false);
    }
  })

  useFrame((state) => {
    if (section !== 1) {
      setValidSkill(false);
    }
  });
  
  return (
    <group {...props} dispose={null}>
      <motion.group
        animate={{
          x: [0, 4, 0, 0, 0],
          rotateY: [0, 0, 0, 1, 0],
          transition: {
            duration: 6,
            repeat: Infinity,
            delay: 1,
          }
        }}
      >
        <Words text={"PHP"} color={validSkill ? '#22bb1d' : '#ff0040'} size={1} rotateY={-1} AxX={-1} AxY={1.5} AxZ={0} />
        <Words text={"Javascript"} color={validSkill ? '#22bb1d' : '#ff0040'} size={0.275} rotateY={-0.6} AxX={-4} AxY={-1} AxZ={2} />
        <group name="Scene">
          <group name="Box015_wire_01_0" >
            <mesh name="Box015_wire_01_0_1" geometry={nodes.Box015_wire_01_0_1.geometry} material={materials.wire_01} />
            <mesh name="Box015_wire_01_0_2" geometry={nodes.Box015_wire_01_0_2.geometry} material={materials.steel_02_01} />
            <mesh name="Box015_wire_01_0_3" geometry={nodes.Box015_wire_01_0_3.geometry} material={materials.steel_02_02} />
            <mesh name="Box015_wire_01_0_4" geometry={nodes.Box015_wire_01_0_4.geometry} material={materials.eyes} />
            <mesh name="Box015_wire_01_0_5" geometry={nodes.Box015_wire_01_0_5.geometry} material={materials.bone} />
            <mesh name="Box015_wire_01_0_6" geometry={nodes.Box015_wire_01_0_6.geometry} material={materials.steel_01_01} />
            <mesh name="Box015_wire_01_0_7" geometry={nodes.Box015_wire_01_0_7.geometry} material={materials.wire_03} />
            <mesh name="Box015_wire_01_0_8" geometry={nodes.Box015_wire_01_0_8.geometry} material={materials.wire_02} />
            <mesh name="Box015_wire_01_0_9" geometry={nodes.Box015_wire_01_0_9.geometry} material={materials.collar} />
            <mesh name="Box015_wire_01_0_10" geometry={nodes.Box015_wire_01_0_10.geometry} material={materials.battery} />
            <mesh name="Box015_wire_01_0_11" geometry={nodes.Box015_wire_01_0_11.geometry} material={materials.steel_02_03} />
            <mesh name="Box015_wire_01_0_12" geometry={nodes.Box015_wire_01_0_12.geometry} material={materials.steel_01_02} />
            <mesh name="Box015_wire_01_0_13" geometry={nodes.Box015_wire_01_0_13.geometry} material={materials['01_-_Default']} />
            <mesh name="Box015_wire_01_0_14" geometry={nodes.Box015_wire_01_0_14.geometry} material={materials.Steel} />
            <mesh name="Box015_wire_01_0_15" geometry={nodes.Box015_wire_01_0_15.geometry} material={materials.bolts} />
            <mesh name="Box015_wire_01_0_16" geometry={nodes.Box015_wire_01_0_16.geometry} material={materials.Material_1573} />
          </group>
        </group>
      </motion.group>
    </group>
  )
}

useGLTF.preload('models/robots/buny_robot/buny.gltf')
