/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\room\myroom.gltf -k 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import { motion } from 'framer-motion-3d';
import * as THREE from 'three';
import { animate, useMotionValue } from 'framer-motion';
import { useFrame } from '@react-three/fiber';

export function Myroom(props) {
  const group = useRef()
  const { section } = props;
  const { nodes, materials } = useGLTF('models/room/myroomScreen.gltf');
  const texture = useTexture('textures/Baked.jpg');
  const textureVideo = useVideoTexture('textures/luffyGear5.mp4');
  
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
      map: texture,
      transparent: true,
      opacity: 1
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42
  });

  const textureMirrorMaterial = new THREE.MeshStandardMaterial({
    color: '#000',
    roughness: 1,
    metalness: 1,
    transparent: true,
    opacity: 0.42
  });

  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);
  const mirrorTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section == 0 ? 1 : 0, {
      duration: 0.8
    });
    animate(glassTextureOpacity, section == 0 ? 0.42 : 0, {
      duration: 0.8
    });
    animate(mirrorTextureOpacity, section == 0 ? 0.42 : 0, {
      duration: 0.8
    });
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
    textureGlassMaterial.opacity = glassTextureOpacity.get();
    textureMirrorMaterial.opacity = mirrorTextureOpacity.get();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Screen"
          geometry={nodes.Screen.geometry}
          position={[-0.277, 1.056, -1.876]}
          rotation={[1.942, -0.015, -1.572]}
        >
          <meshBasicMaterial map={textureVideo} toneMapped={false} />
        </mesh>
        <group name="Bed" position={[0.885, 0, 0.757]} rotation={[-1.591, 0, 3.135]}>
          <mesh name="Bed_Bed_Blanket_0" geometry={nodes.Bed_Bed_Blanket_0.geometry} material={textureMaterial} />
          <mesh name="Bed_Bed_Blanket_0_1" geometry={nodes.Bed_Bed_Blanket_0_1.geometry} material={textureMaterial} />
          <mesh name="Bed_Bed_Blanket_0_2" geometry={nodes.Bed_Bed_Blanket_0_2.geometry} material={textureMaterial} />
          <mesh name="Bed_Bed_Blanket_0_3" geometry={nodes.Bed_Bed_Blanket_0_3.geometry} material={textureMaterial} />
          <mesh name="Bed_Bed_Blanket_0_4" geometry={nodes.Bed_Bed_Blanket_0_4.geometry} material={textureMaterial} />
        </group>
        <group name="Closet" position={[0.813, 0.955, -1.705]}>
          <mesh name="Object_0" geometry={nodes.Object_0.geometry} material={textureMaterial} />
          <mesh name="Object_0_1" geometry={nodes.Object_0_1.geometry} material={textureMirrorMaterial} /> {/* espejo  */}
          <mesh name="Object_0_2" geometry={nodes.Object_0_2.geometry} material={textureMaterial} />
          <mesh name="Object_0_3" geometry={nodes.Object_0_3.geometry} material={textureMaterial} />
          <mesh name="Object_0_4" geometry={nodes.Object_0_4.geometry} material={textureGlassMaterial} />
          <mesh name="Object_0_5" geometry={nodes.Object_0_5.geometry} material={textureMaterial} />
        </group>
        <group name="Table" position={[-1.384, -0.008, 0.548]} rotation={[-1.565, 0, 0]}>
          <mesh name="Furniture_Table_1_M_Furniture_Table_1_0" geometry={nodes.Furniture_Table_1_M_Furniture_Table_1_0.geometry} material={textureMaterial} />
          <mesh name="Furniture_Table_1_M_Furniture_Table_1_0_1" geometry={nodes.Furniture_Table_1_M_Furniture_Table_1_0_1.geometry} material={textureMaterial} />
        </group>
        <motion.mesh
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 1 : 0.5
          }}
          name="Chair"
          geometry={nodes.Chair.geometry}
          material={textureMaterial}
          position={[-1.441, 0, 1.461]}
          rotation={[-Math.PI, 0.057, -Math.PI]}
        />
        <group name="tv"
          position={[-0.277, 1.056, -1.876]}
          rotation={[1.942, -0.015, -1.572]}
        >
          <mesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={textureMaterial} />
          <mesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={textureMaterial} />
          <mesh name="Mesh002_2" geometry={nodes.Mesh002_2.geometry} material={textureMaterial} />
          <mesh name="Mesh002_3" geometry={nodes.Mesh002_3.geometry} material={textureMaterial} />
          <mesh name="Mesh002_4" geometry={nodes.Mesh002_4.geometry} material={textureMaterial} />
          <mesh name="Mesh002_5" geometry={nodes.Mesh002_5.geometry} material={textureMaterial} />
          <mesh name="Mesh002_6" geometry={nodes.Mesh002_6.geometry} material={textureMaterial} />
          <mesh name="Mesh002_7" geometry={nodes.Mesh002_7.geometry} material={textureMaterial} />
        </group>
        <motion.mesh
          name="wado"
          geometry={nodes.wado.geometry}
          material={textureMaterial}

          animate={{
            y: section === 0 ? 0.65 : 2
          }}

          position={[0.357, -1, 0.621]}
          rotation={[-1.563, 0.035, 0.634]}
        />
        <group name="Room">
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={textureMaterial} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={glassTextureOpacity} /> {/* ventana */}
          <mesh name="Plane_4" geometry={nodes.Plane_4.geometry} material={glassTextureOpacity} /> {/* ventana */}
          <mesh name="Plane_5" geometry={nodes.Plane_5.geometry} material={glassTextureOpacity} /> {/* ventana */}
        </group>
        <group name="Pc" position={[-1.414, 1.042, 0.367]} rotation={[-1.571, -0.003, 1.511]}>
          <mesh name="Object_0003" geometry={nodes.Object_0003.geometry} material={textureMaterial} />
          <mesh name="Object_0003_1" geometry={nodes.Object_0003_1.geometry} material={glassTextureOpacity} />
          <mesh name="Object_0003_2" geometry={nodes.Object_0003_2.geometry} material={textureMaterial} />
          <mesh name="Object_0003_3" geometry={nodes.Object_0003_3.geometry} material={textureMaterial} />
          <mesh name="Object_0003_4" geometry={nodes.Object_0003_4.geometry} material={textureMaterial} />
          <mesh name="Object_0003_5" geometry={nodes.Object_0003_5.geometry} material={textureMaterial} />
          <mesh name="Object_0003_6" geometry={nodes.Object_0003_6.geometry} material={textureMaterial} />
          <mesh name="Object_0003_7" geometry={nodes.Object_0003_7.geometry} material={textureMaterial} />
          <mesh name="Object_0003_8" geometry={nodes.Object_0003_8.geometry} material={textureMaterial} />
          <mesh name="Object_0003_9" geometry={nodes.Object_0003_9.geometry} material={textureMaterial} />
          <mesh name="Object_0003_10" geometry={nodes.Object_0003_10.geometry} material={textureMaterial} />
          <mesh name="Object_0003_11" geometry={nodes.Object_0003_11.geometry} material={textureMaterial} />
          <mesh name="Object_0003_12" geometry={nodes.Object_0003_12.geometry} material={textureMaterial} />
        </group>
        <motion.group
          name="Monitor1"
          animate={{
            y: section === 0 ? 0.788 : 2
          }}
          position={[-1.665, 0.788, 0.616]}
          rotation={[-1.571, 0, 0.196]}
        >
          <mesh name="Object_0004" geometry={nodes.Object_0004.geometry} material={textureMaterial} />
          <mesh name="Object_0004_1" geometry={nodes.Object_0004_1.geometry} material={textureMaterial} />
        </motion.group>
        <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={textureMaterial} position={[-1.468, 0.798, 0.787]} rotation={[0, 0.119, 0]} />
        <motion.group name="Monitor2"
          scale={[0, 0, 0]}
          animate={{
            scale: section === 0 ? 1 : 2
          }}
          position={[-1.282, 0.795, 0.634]}
          rotation={[-0.787, -0.125, -0.124]}
        >         
          <mesh name="Material2053" geometry={nodes.Material2053.geometry} material={textureMaterial} />
          <mesh name="Material2053_1" geometry={nodes.Material2053_1.geometry} material={textureMaterial} />
          <mesh name="Material2053_2" geometry={nodes.Material2053_2.geometry} material={textureMaterial} />
          <mesh name="Material2053_3" geometry={nodes.Material2053_3.geometry} material={textureMaterial} />
          <mesh name="Material2053_4" geometry={nodes.Material2053_4.geometry} material={textureMaterial} />
        </motion.group>
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={textureMaterial} position={[-1.193, 0.793, 0.761]} rotation={[-1.565, 0, -0.063]} />
        <group name="cel" position={[-1.444, 0.788, 0.649]} rotation={[0, 1.075, 0]}>
          <mesh name="Object_0002" geometry={nodes.Object_0002.geometry} material={textureMaterial} />
          <mesh name="Object_0002_1" geometry={nodes.Object_0002_1.geometry} material={textureMaterial} />
          <mesh name="Object_0002_2" geometry={nodes.Object_0002_2.geometry} material={textureMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/room/myroomScreen.gltf');
useTexture.preload('textures/Baked.jpg');
